name: Selenium Tests

on:
  push:
    branches:
      - main  # Remplacez par le nom de votre branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Update pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run Selenium Tests
      run: |
        mkdir pytest-results
        python -m pytest --junitxml=pytest-results/pytest-results.xml run_test.py

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest-results

      
